OrderManagementSystem/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderManagementSystem.DTOs.CustomerDTOs;
using OrderManagementSystem.Models;
using OrderManagementSystem.Service.CustomerSer;
using System.Diagnostics;

namespace OrderManagementSystem.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ILogger<CustomerController> logger;
        private readonly ICustomerService service;

        public CustomerController(ILogger<CustomerController> logger, ICustomerService service)
        {
            this.logger = logger;
            this.service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var customer = await service.GetCustomersAsync();  // Fetch all persons from the database
            return View(customer);  // Pass the list of persons to the view
        }
        
        [HttpGet]
        public async Task<IActionResult> CustomersOrders() {

            IEnumerable<CustomersOrderDTO> customersOrders = await service.GetCustomersOrdersAsync();  // Fetch all persons from the database
            return View(customersOrders);
        }
        [HttpPost]
        public async Task<JsonResult> UpdateCustomer(CustomerDTO updatedCustomer) 
        {
            if (!ModelState.IsValid) {
                return Json(new { success = false, errorMessage = "Invalid data", errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage) });
            }
            try { 
                            
                await service.UpdateCustomerAsync(updatedCustomer);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }
           
        }
        [HttpDelete]
        public async Task<JsonResult> DeleteCustomer(int id)
        {
            try
            {
                await service.DeleteCustomerByIdAsync(id);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }
        [HttpPost]
        public async Task<JsonResult> InsertCustomer(InsertCustomerDTO insertCustomerDTO)
        {
            if (!ModelState.IsValid) 
            {
                return Json(new
                {
                    success = false,
                    errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
                });
            }
            try
            {
               var updatedCustomer = await service.InsertCustomerAsync(insertCustomerDTO);
               return Json(new { success = true,customer = updatedCustomer });;  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OrderManagementSystem/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OrderManagementSystem.DTOs.OrderDTOs;
using OrderManagementSystem.Models;
using OrderManagementSystem.Service.OrderService;
using System.Diagnostics;

namespace OrderManagementSystem.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService service;
        private readonly ILogger<OrderController> _logger;

        public OrderController(ILogger<OrderController> logger, IOrderService service)
        {
            this.service = service;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await service.GetOrdersAsync();
            return View(orders);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateOrder(OrderDTO updatedOrder)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { 
                    success = false, 
                    errorMessage = "Invalid data", 
                    errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage) });
            }
            try
            {
                await service.UpdateOrderAsync(updatedOrder);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }
        [HttpDelete]
        public async Task<JsonResult> DeleteOrder(int id)
        {
            try
            {
                await service.DeleteOrderByIdAsync(id);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }
        [HttpPost]
        public async Task<JsonResult> InsertOrder(InsertOrderDTO insertOrderDTO)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    success = false,
                    errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
                });
            }
            try
            {
                var updatedOrder= await service.InsertOrderAsync(insertOrderDTO);
                return Json(new { success = true, order = updatedOrder }); ;  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OrderManagementSystem/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using OrderManagementSystem.DTOs.OrderItemDTOs;
using OrderManagementSystem.Models;
using OrderManagementSystem.Service.OrderItemService;
using System.Diagnostics;

namespace OrderManagementSystem.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly IOrderItemService service;
        private readonly ILogger<OrderItemController> _logger;

        public OrderItemController(ILogger<OrderItemController> logger, IOrderItemService service)
        {
            this.service = service;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var orderItems = await service.GetOrderItemsAsync();
            return View(orderItems);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateOrderItem(OrderItemDTO updatedOrderItem)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    success = false,
                    errorMessage = "Invalid data",
                    errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
                });
            }
            try
            {
                await service.UpdateOrderItemAsync(updatedOrderItem);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }
        [HttpDelete]
        public async Task<JsonResult> DeleteOrderItem(int id)
        {
            try
            {
                await service.DeleteOrderItemByIdAsync(id);
                return Json(new { success = true });  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }
        [HttpPost]
        public async Task<JsonResult> InsertOrder(InsertOrderItemDTO insertOrderItemDTO)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    success = false,
                    errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)
                });
            }
            try
            {
                var updatedOrderItem = await service.InsertOrderItemAsync(insertOrderItemDTO);
                return Json(new { success = true, order = updatedOrderItem }); ;  // Return a success response
            }
            catch (Exception ex)
            {
                // If there's an error, return a failure response with the error message
                return Json(new { success = false, errorMessage = ex.Message });
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OrderManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] OrderManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrderManagementSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/DataTables/datatables.css" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OrderManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="CustomersOrders">CustomersOrder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderItem" asp-action="Index">OrderItem</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - OrderManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script src="~/lib/DataTables/datatables.js"> </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>